---

- name: Playbook installing httpd and start httpd service
  hosts: webservers
  become: yes	
  tasks:

  - name: Installing httpd
    yum:
      name: httpd
      state: present

  - name: Starting httpd and enabling it
    service:
      name: httpd
      state: started
      enabled: yes
