---

- name: playbook to test vars
  hosts: webservers
  become: yes
  gather_facts: true
  
  vars:
    target_service: httpd
    target_state: started
  
  tasks:

  - name: Start httpd service
    service:
      name: "{{ target_service }}"
      state: "{{ target_state }}" 
    
