---

- name: Adding several users
  hosts: webservers
  become: yes
  gather_facts: true
  vars:
    users:
    - bob
    - joe
    - moe
  tasks:
  
  - name: adding users
    user:
      name: "{{ item }}"
      state: present
    with_items: "{{ users }}"
